// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fzbppsomvfhjwxzicbli.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6YnBwc29tdmZoand4emljYmxpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MzQ1NzcsImV4cCI6MjA3MDQxMDU3N30.JOAdZgUjYGFqGw4Mmt9vCKZixbEeTjvXrpBCvJXGgRI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});